```{r}
library(readxl)
library(limma)
library(ape)
library(dendextend)
library(RColorBrewer)
library(pvclust)
library(gplots)
library(NMF)
library(vegan)
library(Biobase)
library(DT)
library(ggplot2)
library(impute)
library(ggrepel)
```

```{r}
data <- read.csv("C:\\Users\\Derin\\Desktop\\peaks_data.csv", sep=',')
colSums(is.na(data[, 4:ncol(data)]))

duplicates <- data$Gene_id[duplicated(data$Gene_id)]
for (dup in duplicates) {
  indexes <- which(data$Gene_id == dup)
  data$Gene_id[indexes] <- paste0(dup, "_", seq_along(indexes))
}

rownames(data) <- data$Gene_id
df <- data[, 4:ncol(data)]
genes_with_NA <- names(which(rowSums(is.na(df)) > ncol(df)/2))
df <- df[!rownames(df) %in% genes_with_NA,]

```

```{r}
df <- t(as.matrix(df))
knn_df <- impute.knn(df, k = 5)
knn_df <- knn_df$data
knn_df <- as.data.frame(knn_df)
knn_df <- t(as.matrix(knn_df))
df_exp <- factor(c(rep("Control", 14), rep("HVC", 20)))
```

```{r}
pal <- brewer.pal(n = 9, name = "Set1")
cols <- pal[df_exp]
boxplot(knn_df, outline = FALSE, main = "Raw data", col = cols)
legend("topright", levels(df_exp), fill = pal, bty = "n", xpd = T)
```

```{r}
df_log <- log2(knn_df)
df_norm <- normalizeQuantiles(as.matrix(df_log))
boxplot(df_norm, outline = FALSE, main = "Normalized", col = cols)
legend("topright", levels(df_exp), fill = pal, bty = "n", xpd = T)
```

```{r}
df_pca <- t(df_norm)
terapod_pca <- rda(df_pca, scale = TRUE)

rownames(df_pca) <- colnames(df_norm)

df_scores <- data.frame(df_pca,
                        scores(terapod_pca, display = "sites", choices = c(1, 2, 3), scaling = "sites"))

p_scores <- ggplot(df_scores, aes(x = PC1, y = PC2)) + 
  geom_point(aes(color = rownames(df_pca)), alpha = 0.5) +
  coord_equal(xlim = c(-3, 3), ylim = c(-3, 3)) + ggtitle(label = "PCA Ordination") + theme_bw()
p_scores
```


```
                                                    DE
```

```{r}
expr_data <- as.matrix(df_norm)

# Samples
df_exp <- df_exp[-1]
pheno_data <- data.frame(df_exp)
rownames(pheno_data) <- colnames(df_norm)
pheno_metadata <- data.frame(
  labelDescription = c("Experimental condition"),
  row.names=c("Condition"))
pheno_data <- new("AnnotatedDataFrame",
                 data = pheno_data,
                 varMetadata = pheno_metadata)

# Features
feature_data <- data.frame(Prot = rownames(expr_data))
rownames(feature_data) <- rownames(expr_data)
feature_metadata <- data.frame(
  labelDescription = c("Protain name"),
  row.names = c("Protain"))
f_data <- new("AnnotatedDataFrame",
              data = feature_data,
              varMetadata = feature_metadata)

# Merge
exp_set <-
  ExpressionSet(assayData = expr_data,
                phenoData = pheno_data,
                featureData = f_data)
```

```{r}
X <- model.matrix(~ sample(df_exp), pData(exp_set))
fit <- lmFit(exp_set, design = X, method = "robust", maxit = 1000)
efit <- eBayes(fit)
```
```{r}
MA_limma <- function(efit, coef, n = 10, signif = TRUE, fdr = 0.05, lfc = 0, text = TRUE, cex.text = 0.8, col.text = "grey20", main = "MA-plot", xlab = "Average log-expression", ylab = "Expression log-ratio", pch = 19, pch.signif = 21, col = "darkgreen", alpha = 0.3, cex = 0.3, ...){

  R <- efit$coefficients[, coef]
  I <- efit$Amean

  col_btransp <- adjustcolor(col, alpha.f = alpha)

  plot(I, R, cex = cex, main = main, pch = pch, xlab = xlab, ylab = ylab, col = col_btransp, ...)
  abline(h = 0)

  if(signif){
    sign <- p.adjust(efit$p.value[, coef], method = "BH") <= fdr
    large <- abs(efit$coefficients[, coef]) >= lfc
    points(I[sign & large], R[sign & large], cex = cex*2, col = "orange2", pch = pch.signif)
  }

  if(text){
    ord <- order(efit$lods[, coef], decreasing = TRUE)
    top_n <- ord[1:n]
    text(I[top_n], R[top_n], labels = efit$genes[top_n, ], pos = 4, cex = cex.text, col = col.text)
  }
}


MA_limma(efit, coef = 2, n = 30)
```
```{r}
my_list <- topTable(efit, coef = 2, n = 30)
dif_exp_set <- exp_set[fData(exp_set)$Prot %in% my_list$Prot, ]
```

```{r fig.height=10, fig.width=15}
dat <- as.matrix(exprs(dif_exp_set))

column_means <- apply(dat, 2, function(x) {
  mean(x[is.finite(x)])
})


dat_cleaned <- apply(dat, 2, function(x) {
  x[is.infinite(x) | is.nan(x)] <- column_means[is.infinite(x) | is.nan(x)]
  return(x)
})


dat_final <- apply(dat_cleaned, 2, function(x) {
  x[is.finite(x)] <- x[is.finite(x)] - column_means[is.finite(x)]
  return(x)
})

pal_blue_red <- colorpanel(75, low = "steelblue", mid = "black", high = "red")
heatmap.2(dat_final, col = pal_blue_red, scale = "row", key = TRUE, symkey = FALSE, density.info = "none", trace = "none", cexRow = 0.9, cexCol = 1, margins = c(4, 3), keysize = 0.8, key.par = list(mar = c(3, 0.1, 3, 0.1)))
```

```{r}
topTable(efit, coef = 2)
numGenes <- nrow(exprs(exp_set))
full_list <- topTable(efit, number = numGenes)
full_list <- full_list[full_list$adj.P.Val <= 0.05,]
```

```{r}
MA_limma(efit, coef = 2, n = 4)
MA_limma(efit, coef = 2, n = 80, text = F, lfc = 1)
```

```{r}
my_list <- full_list
dif_exp_set <- exp_set[fData(exp_set)$Prot %in% my_list$Prot, ]
volcano_list <- full_list
volcano1 <- ggplot(data = volcano_list, aes(x = logFC, y = -log10(adj.P.Val))) + geom_point()

volcano2 <- volcano1 + geom_vline(xintercept=c(-1, 1), col="red") +
  geom_hline(yintercept=-log10(0.05), col="red")

volcano_list$diffexpressed <- "NO"  
```

```{r}
volcano_list$diffexpressed[volcano_list$logFC > 1 & volcano_list$adj.P.Val < 0.05] <- "UP"
volcano_list$diffexpressed[volcano_list$logFC < -1 & volcano_list$adj.P.Val< 0.05] <- "DOWN"

volcanodif1 <- ggplot(data = volcano_list, aes(x = logFC, y = -log10(adj.P.Val), col = diffexpressed)) + geom_point() + theme_minimal()
volcanodif2 <- volcanodif1 + geom_vline(xintercept=c(-1, 1), col="red") +
  geom_hline(yintercept=-log10(0.05), col="red")

volcano_list$Prot <- as.character(volcano_list$Prot)
volcano_list$delabel <- NA
volcano_list$delabel[volcano_list$diffexpressed != "NO"] <- volcano_list$Prot[volcano_list$diffexpressed != "NO"]

plot_proteins <- ggplot(data=volcano_list, aes(x=logFC, y=-log10(adj.P.Val), col=diffexpressed, label=delabel)) + 
  geom_point() + 
  theme_minimal() +
  geom_text_repel(size=3, colour = 'black', max.overlaps = 30)

plot_final <- plot_proteins + geom_vline(xintercept=c(-1, 1), col="red") + geom_hline(yintercept=-log10(0.05), col="red")
plot_final
```


```
According to DE results between control individuals and those with heart valve calcification suggests involvement in various biological processes, including epithelial integrity, inflammation, chromatin remodeling, DNA repair, and cellular signaling.
Increased KRT17 expression may also reflect cellular stress responses induced by pathological conditions, including calcification-related stress in heart valve tissues.
Changes in H2AW expression may affect the differentiation status of valve interstitial cells or their response to calcification-inducing signals due to histone modifications level alteration. 
Batch effect wasnt indicated in PCA Ordination plot, heat map graph showed prominent contrast
```
